
version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    restart: unless-stopped

#version: '3.7'
#services:
#  mongodb_container:
#    image: mongo:latest
#    environment:
#      #This user is created in the admin authentication database and given the role of root, which is a "superuser" role.
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: password
#    ports:
#      - 27017:27017
#    volumes:
#      - mongodb_data_container:/data/db
#
#volumes:
#  mongodb_data_container: